name: seedstubs
description: Deterministic and seeded stubs.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.0
  json_annotation: ^3.0.1
  shelf: ^0.7.5

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
